# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: ci
on:
  push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    permissions:
      packages: read
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x]
        os: [ubuntu-22.04, ubuntu-22.04-arm, windows-2022, macos-14]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
      - if: runner.os == 'Linux'
        run: sudo apt-get install -y build-essential libgl1-mesa-dri libglapi-mesa
                                     libglew-dev libglu1-mesa-dev libosmesa6
                                     libxi-dev mesa-utils pkg-config
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_build_from_source: true
          # npm_config_build_from_source is used to force npm post install scripts to build native modules from source instead of downloading prebuilt binaries.
      - run: npm run build --if-present
      - if: runner.os == 'Linux'
        run: xvfb-run glxinfo
      - if: runner.os == 'Linux'
        run: xvfb-run npm test
      - if: runner.os != 'Linux'
        run: npm test
