# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: ci
on:
  push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install -y build-essential libgl1-mesa-dri libglapi-mesa
                                     libglew-dev libglu1-mesa-dev libosmesa6
                                     libxi-dev mesa-utils pkg-config
      - run: npm ci
      - run: npm run build --if-present
      - if: startsWith(matrix.os, 'ubuntu')
        run: xvfb-run npm test
      - if: "!startsWith(matrix.os, 'ubuntu')"
        run: npm test

  windows-nodejs-v20:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: uninstall nodejs
      run: choco uninstall -y nodejs nodejs.install
    - name: install nodejs
      run: choco install -y nodejs.install --version=20.11.1
    - name: update npm
      run: npm install --location=global npm@latest
    - name: echo node version
      run: node --version
    - name: install python
      run: choco install -y python3
    - name: install microsoft-build-tools
      run: choco install -y microsoft-build-tools
    - name: submodule init
      run: git submodule init
    - name: submodule update
      run: git submodule update
    - name: install dependencies
      run: npm install
    - name: rebuild
      run: npm run rebuild
    - name: run test
      run: npm test

  windows-nodejs-v18:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: uninstall nodejs
      run: choco uninstall -y nodejs nodejs.install
    - name: install nodejs
      run: choco install -y nodejs.install --version=18.18.2
    - name: update npm
      run: npm install --location=global npm@latest
    - name: echo node version
      run: node --version
    - name: install python
      run: choco install -y python3
    - name: install microsoft-build-tools
      run: choco install -y microsoft-build-tools
    - name: submodule init
      run: git submodule init
    - name: submodule update
      run: git submodule update
    - name: install dependencies
      run: npm install
    - name: rebuild
      run: npm run rebuild
    - name: run test
      run: npm test
